apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: roboshop
  # these are replica set labels
  labels:
    project: roboshop
    component: redis
    tier: db
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      project: roboshop
      component: redis
      tier: db
  # pod definition
  template:
    metadata:
      labels:
        project: roboshop
        component: redis
        tier: db
    spec:
      containers:
      - name: redis
        image: redis:7.0
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
         tcpSocket:
           port: 6379
         initialDelaySeconds: 6
         periodSeconds: 6
---
apiVersion: v1
kind: Service
metadata:
   name: redis
   namespace: roboshop
spec: 
  selector:
     project: roboshop 
     component: redis
     tier: db
  ports:
   - protocol: TCP
     port: 6379 # service port
     targetPort: 6379  #. container port